package com.developer.nefarious.zjoule.plugin.chat.openai;

import java.util.List;

import com.google.gson.annotations.SerializedName;

/**
 * Represents the response body from an OpenAI chat completion API request.
 * This class encapsulates information about the response, including choices,
 * token usage, and metadata.
 */
public class OpenAIRequestResponse {

    /**
     * Represents a single choice in the response from the OpenAI API.
     * A choice contains the generated message, its index, and the reason why the generation finished.
     */
    public static class Choice {

        /** The index of this choice in the response. */
        private int index;

        /** The reason why the response generation finished (e.g., "length", "stop"). */
        @SerializedName("finish_reason")
        private String finishReason;

        /** The message generated by the OpenAI model for this choice. */
        private OpenAIChatMessage message;

        /**
         * Retrieves the reason why the response generation finished.
         *
         * @return the finish reason as a {@link String}.
         */
        public String getFinishReason() {
            return finishReason;
        }

        /**
         * Sets the reason why the response generation finished.
         *
         * @param finishReason the finish reason as a {@link String}.
         */
        public void setFinishReason(final String finishReason) {
            this.finishReason = finishReason;
        }

        /**
         * Retrieves the index of this choice in the response.
         *
         * @return the index as an {@code int}.
         */
        public int getIndex() {
            return index;
        }

        /**
         * Sets the index of this choice in the response.
         *
         * @param index the index as an {@code int}.
         */
        public void setIndex(final int index) {
            this.index = index;
        }

        /**
         * Retrieves the message generated by the OpenAI model for this choice.
         *
         * @return the {@link OpenAIChatMessage}.
         */
        public OpenAIChatMessage getMessage() {
            return message;
        }

        /**
         * Sets the message generated by the OpenAI model for this choice.
         *
         * @param message the {@link OpenAIChatMessage}.
         */
        public void setMessage(final OpenAIChatMessage message) {
            this.message = message;
        }
    }

    /**
     * Represents the token usage details in the OpenAI API response.
     * Includes the number of tokens used for the prompt, completion, and total.
     */
    public static class Usage {

        /** The number of tokens used for the prompt. */
        @SerializedName("prompt_tokens")
        private int promptTokens;

        /** The number of tokens used for the completion. */
        @SerializedName("completion_tokens")
        private int completionTokens;

        /** The total number of tokens used for the request. */
        @SerializedName("total_tokens")
        private int totalTokens;

        /**
         * Retrieves the number of tokens used for the prompt.
         *
         * @return the prompt tokens as an {@code int}.
         */
        public int getPromptTokens() {
            return promptTokens;
        }

        /**
         * Sets the number of tokens used for the prompt.
         *
         * @param promptTokens the prompt tokens as an {@code int}.
         */
        public void setPromptTokens(final int promptTokens) {
            this.promptTokens = promptTokens;
        }

        /**
         * Retrieves the number of tokens used for the completion.
         *
         * @return the completion tokens as an {@code int}.
         */
        public int getCompletionTokens() {
            return completionTokens;
        }

        /**
         * Sets the number of tokens used for the completion.
         *
         * @param completionTokens the completion tokens as an {@code int}.
         */
        public void setCompletionTokens(final int completionTokens) {
            this.completionTokens = completionTokens;
        }

        /**
         * Retrieves the total number of tokens used for the request.
         *
         * @return the total tokens as an {@code int}.
         */
        public int getTotalTokens() {
            return totalTokens;
        }

        /**
         * Sets the total number of tokens used for the request.
         *
         * @param totalTokens the total tokens as an {@code int}.
         */
        public void setTotalTokens(final int totalTokens) {
            this.totalTokens = totalTokens;
        }
    }

    /** The unique identifier for the response. */
    private String id;

    /** The object type of the response (e.g., "chat.completion"). */
    private String object;

    /** The timestamp when the response was created. */
    private long created;

    /** The model used to generate the response. */
    private String model;

    /** A list of choices returned by the OpenAI API. */
    private List<Choice> choices;

    /** The token usage details for the request. */
    private Usage usage;

    /**
     * Retrieves the unique identifier for the response.
     *
     * @return the response ID as a {@link String}.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the unique identifier for the response.
     *
     * @param id the response ID as a {@link String}.
     */
    public void setId(final String id) {
        this.id = id;
    }

    /**
     * Retrieves the object type of the response.
     *
     * @return the object type as a {@link String}.
     */
    public String getObject() {
        return object;
    }

    /**
     * Sets the object type of the response.
     *
     * @param object the object type as a {@link String}.
     */
    public void setObject(final String object) {
        this.object = object;
    }

    /**
     * Retrieves the timestamp when the response was created.
     *
     * @return the creation timestamp as a {@code long}.
     */
    public long getCreated() {
        return created;
    }

    /**
     * Sets the timestamp when the response was created.
     *
     * @param created the creation timestamp as a {@code long}.
     */
    public void setCreated(final long created) {
        this.created = created;
    }

    /**
     * Retrieves the model used to generate the response.
     *
     * @return the model as a {@link String}.
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the model used to generate the response.
     *
     * @param model the model as a {@link String}.
     */
    public void setModel(final String model) {
        this.model = model;
    }

    /**
     * Retrieves the list of choices returned by the OpenAI API.
     *
     * @return a {@link List} of {@link Choice} objects.
     */
    public List<Choice> getChoices() {
        return choices;
    }

    /**
     * Sets the list of choices returned by the OpenAI API.
     *
     * @param choices a {@link List} of {@link Choice} objects.
     */
    public void setChoices(final List<Choice> choices) {
        this.choices = choices;
    }

    /**
     * Retrieves the token usage details for the request.
     *
     * @return the {@link Usage} object containing token usage information.
     */
    public Usage getUsage() {
        return usage;
    }

    /**
     * Sets the token usage details for the request.
     *
     * @param usage the {@link Usage} object containing token usage information.
     */
    public void setUsage(final Usage usage) {
        this.usage = usage;
    }
}
